
workflows:
  flutter-build:
    name: Build APK
    max_build_duration: 30
    environment:
      flutter: "3.7.0"
    scripts:
      - flutter pub get
      - flutter build apk
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
