workflows:
  flutter-build:
    name: Build APK
    max_build_duration: 30
    environment:
      flutter: stable
      working_directory: .  # change if your project is inside a folder

    scripts:
      - name: Clean and install dependencies
        script: |
          rm -f pubspec.lock
          flutter pub upgrade

      - name: Build APK
        script: flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
